import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { auth, ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import GlobalProvider from "../context/GlobalContext";
import { ThemeButton } from "@/components/ThemButton";
export const metadata: Metadata = {
  title: "Tasks Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();
  return (
    <ClerkProvider>
      <html lang="en" className="dark:bg-[#181818] bg-slate-300">
        <body className={inter.className}>
          <GlobalProvider>
            {userId && <SideBar />}
            <main className="w-full h-full overflow-hidden rounded-2xl dark:bg-gray-800 bg-slate-400 p-6">
              <div className="dark:bg-slate-900 bg-slate-500 rounded-2xl p-4 flex justify-between items-center ">
                <h1 className="md:text-2xl font-bold">Tasks Manager</h1>
                <ThemeButton />
              </div>
              {children}
            </main>
          </GlobalProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
