import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });
import GlobalProvider from "../context/GlobalContext";
export const metadata: Metadata = {
  title: "Tasks Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <SideBar />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
