import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { auth, ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import GlobalProvider from "../context/GlobalContext";
export const metadata: Metadata = {
  title: "Tasks Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <GlobalProvider>
            {userId && <SideBar />}
            {children}
          </GlobalProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
